{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: isvgimconfig
  namespace: {{ .Values.namespace }}
data:
  {{- $server := deepCopy .Values.server                                  }}
  {{- $_ := set $server.flags "enableFIPS" (.Values.fips | default false) }}
  config.yaml: |
    version: '24.12'
    general:
      install:
        createTablespace: {{ .Values.general.install.createTablespace }}
      license:
        activationKey: {{ .Values.general.license.activationKey | default "null" }}
        accepted: {{ .Values.general.license.accepted }}
        riskKey: {{ .Values.general.license.riskKey | default "null" }}
    server: {{- $server | toYaml | nindent 6 }}
    {{- if .Values.oidc}}
    oidc: {{- .Values.oidc | toYaml | nindent 6 }}
    {{- end }}

