{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
{{- if not (.Values.general.install.externalSecret).extcreds }}
apiVersion: v1
data:
  EXT_LDAP_PASSWORD: {{ required "LDAP_PASSWORD missing!" .Values.LDAP_PASSWORD | b64enc }}
  EXT_DB_PASSWORD:  {{ required "DB_PASSWORD missing!" .Values.DB_PASSWORD | b64enc }}
  EXT_DBADMIN_PASSWORD: {{ required "DBADMIN_PASSWORD missing!" .Values.DBADMIN_PASSWORD | b64enc }}
  EXT_APPSERVER_PASSWORD: {{ required "APPSERVER_PASSWORD missing!" .Values.APPSERVER_PASSWORD | b64enc }}
  EXT_ISIMSYSTEM_PASSWORD: {{ required "ISIMSYSTEM_PASSWORD missing!" .Values.ISIMSYSTEM_PASSWORD | b64enc }}
  EXT_MAIL_PASSWORD: {{ default "" .Values.MAIL_PASSWORD | b64enc }}
  EXT_EURBIND_PASSWORD: {{ default "" .Values.EURBIND_PASSWORD | b64enc }}
  EXT_ITIMCIPHER_KEY: {{ default "" .Values.ITIMCIPHER_KEY | b64enc }}
kind: Secret
metadata:
  name: extcreds
  namespace: {{ .Values.namespace }}
{{- end }}
