



# Entity Index Mapping
policy.index.name=poc_zt_policy_policydocs
policy_history.index.name=poc_zt_policy_history
tenant.index.name=poc_zt_tenant_tenantdocs
policy_violation.index.name=poc_zt_pv_pvdocs
user.index.name=poc_zt_pv_pvdocs
device.index.name=poc_zt_pv_pvdocs
policy_violation_history.index.name=poc_zt_pv_history
user_history.index.name=poc_zt_user_history
device_history.index.name=poc_zt_device_history
policy.index.tenant.key=tntId
entity_sync.index.tenant.key=glbCxt.tntId

#Scripted upsert properties
policy_violation.index.upsert.enabled=true
policy_violation.index.stored.script.enabled=true
policy_violation.index.stored.script.id=violation-upsert
policy_violation.index.stored.script.params=type:type, policyInfo_policyId:policyInfo_policyId ,policyInfo_policyName:policyInfo_policyName ,policyInfo_policyType:policyInfo_policyType ,ruleInfo_ruleId:ruleInfo_ruleId ,ruleInfo_ruleName:ruleInfo_ruleName ,devInfo_devId:devInfo_devId ,devInfo_devName:devInfo_devName ,devInfo_managedStatus:devInfo_managedStatus ,devInfo_platformName:devInfo_platformName ,eventInfo_evtSubType:eventInfo_evtSubType ,eventInfo_evtTs:eventInfo_evtTs ,eventInfo_procTs:eventInfo_procTs ,eventInfo_srcEvtId:eventInfo_srcEvtId ,eventInfo_type:eventInfo_type ,eventInfo_startTs:eventInfo_startTs ,eventInfo_endTs:eventInfo_endTs ,eventInfo_count:eventInfo_count ,usrInfo_usrId:usrInfo_usrId ,usrInfo_domain:usrInfo_domain ,usrInfo_mailId:usrInfo_mailId ,usrInfo_userSource:usrInfo_userSource ,usrInfo_usrName:usrInfo_usrName ,associatedEntities:associatedEntities ,crtTime:crtTime ,critical:critical ,dip:dip ,deviceId:deviceId ,eventType:eventType ,high:high ,id:id ,isDeleted:isDeleted ,low:low ,medium:medium ,modTime:modTime ,policyId:policyId ,rollupEntities:rollupEntities ,score:score ,severity:severity ,tntId:tntId ,tags:tags ,type:type ,userId:userId
# Use local script if stored script is false
policy_violation.index.script=

#State clean
stateclean.deleted.tenants=

# Database Details
db.servername=test.ibm.com
db.username=db2inst1
db.port=50000
db.database.name=TEST
db.schema=ITIMUSER
db.sslEnabled=false

policy_violation.table.name=pv_violation
policy_violation_history.table.name=pv_violation_history
user_history.table.name=user_history
device_history.table.name=device_history
account_history.table.name=account_history
policy.table.name=policies
application_history.table.name=application_history
entitlement_history.table.name=entitlement_history
assignment_history.table.name=assignment_history
risk_history.table.name=risk_history
policy_actions.table.name=policy_actions
remediation_actions.table.name=remediation_actions

#MQ details
mq.hostname=mqshare
mq.port=1414
mq.user=app
mq.queueManager=ISVGQMgrShared
mq.channel=DEV.SHARED.SVRCONN
mq.sslEnabled=true
mq.supportedCipher=*TLS12ORHIGHER

mq.dataSourceQueueName=isvg_risk_input
mq.policySourceQueueName=isvg_risk_input
mq.dataOutSourceQueueName=isvg_risk_output
mq.violationOutQueueName=isvg_risk_violations

