general:
  install:
    createTablespace: true
    deployIsvdi: true
    deployDb: true
    deployLdap: true
    deployIsvart: false
    externalSecret:
      extcreds: false
      isvdcerts: false
      isvdcred: false
      isvdicerts: false
      isvgimcerts: false
      metricscreds: false
      mqcerts: false
      mqcreds: false
      oidccreds: false
      pgcerts: false
      pgcreds: false
      regcred: false
  license:
    activationKey:
    accepted: false
    ldapKey:
    isvdiKey:
    isvartKey:
    riskKey:
db:
  user: postgres
  # DO NOT STORE sensitive data here! See documentation for secure alternatives!
  # password:
  dbtype:
  ip:
  port:
  name: ivig
  admin: postgres
  # DO NOT STORE sensitive data here! See documentation for secure alternatives!
  # adminPwd:
  isOracleServiceName: true
  security.protocol: ssl
  tablespace.location.data: /var/lib/postgresql/data/isvgimdata
  tablespace.location.indexes: /var/lib/postgresql/data/isvgimindexes
ldap:
  security.principal: cn=root
  # DO NOT STORE sensitive data here! See documentation for secure alternatives!
  # security.credentials:
  defaulttenant.id: demo
  organization.name: Demo
  ldapserver.ip:
  ldapserver.port:
  ldapserver.root: dc=ivig
  security.protocol: ssl
mail:
  authentication.type: basic
  baseurl: https://foo.com/
  from: ivig@foo.com
  host: mailservice.mailpit.svc.cluster.local
  smtp.port: 1025
  smtp.starttls.enable: false
  smtp.auth: true
  smtp.auth.user: ivig
  # DO NOT STORE sensitive data here! See documentation for secure alternatives!
  # smtp.auth.password:
office365:
  monitoring.enabled: false
  user.id:
  tenant.id:
  client.id:
  client.secret:
  scan.interval.minutes:
  graph.token.endpoint:
  graph.messages.endpoint:
  graph.user.agent:
server:
  options:
  - name: libertyMetrics
    enabled: false
    data:
    - name: userName
      value: null
    - name: password
      # LEAVE IT SET TO null to use more secure alternatives!
      value: null
  flags:
    disableTLSv12: false
    # DO NOT USE `enableFIPS` here. Use `fips` in `values.yaml`!
    # enableFIPS: false
    secureSessionCookies: true
    globalHSTS: true
    hideServerVersion: false
  hostname: null
  truststore:
  - '@isvgimRootCA.crt'
  keystore: null
