{{/*
Copyright IBM Corp. 2026
SPDX-License-Identifier: MIT
*/}}
{{- if .Values.general.install.deployIsvdi }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: isvdi
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.services.isvdi.replicas | default 1 }}
  {{- if eq .Values.storage.mode "ReadWriteOnce" }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      app: isvdi
  template:
    metadata:
      labels:
        app: isvdi
        {{- include "extra" (list . "labels.pod.isvdi") }}
      annotations:
        {{- include "extra" (list . "annotations.pod.isvdi") }}
    spec:
      {{- if not .Values.isOpenShift }}
      securityContext:
        fsGroup: 0
      {{- end }}
      volumes:
      - name: config
        projected:
          defaultMode: 0640
          sources:
          - configMap:
              name: isvgimsdi
          - secret:
              name: isvdicerts
      - name: init-script
        projected:
          defaultMode: 0755
          sources:
          - configMap:
              name: isvgimsdi
              items:
                - key: setHostname.sh
                  path: setHostname.sh
                - key: call-adapter-init-scripts.sh
                  path: call-adapter-init-scripts.sh
                - key: patch-java.security-for-fips_11.0.0.1.sh
                  path: patch-java.security-for-fips_11.0.0.1.sh
      - name: adapters
        persistentVolumeClaim:
          claimName: isvdi-pvc
      imagePullSecrets:
      - name: regcred
      containers:
      - name: isvdi
        image: {{ .Values.images.isvdi }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.services.isvdi.ports.api }}
          name: api
          protocol: TCP
        - containerPort: {{ .Values.services.isvdi.ports.object }}
          name: object
          protocol: TCP
        env:
        - name: YAML_CONFIG_FILE
          value: /tmp/isvgimsdi/isvdi_config.yaml
        - name: TZ
          value: ":{{ .Values.timezone }}"
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        volumeMounts:
        - name: config
          mountPath: /tmp/isvgimsdi
        - name: adapters
          mountPath: /opt/IBM/svgadapters
        - name: init-script
          mountPath: /home/isvdi/setHostname.sh
          subPath: setHostname.sh
        - name: init-script
          mountPath: /home/isvdi/call-adapter-init-scripts.sh
          subPath: call-adapter-init-scripts.sh
        - name: init-script
          mountPath: /home/isvdi/patch-java.security-for-fips_11.0.0.1.sh
          subPath: patch-java.security-for-fips_11.0.0.1.sh
{{- end }}
