#********************************************************************
#* Copyright IBM Corp. 2026
#* SPDX-License-Identifier: MIT
#********************************************************************





###########################################################
## Authentication information
###########################################################
# Indicates the type of credentials required by end-user
# for authentication. Choices are: simple, certificate
enrole.authentication.requiredCredentials=simple

# Supported authentication providers
# simple provider
enrole.authentication.provider.simple=\
    factory=com.ibm.itim.authentication.simple.SimpleAuthenticationProviderFactory
# service provider
enrole.authentication.provider.service=\
    factory=com.ibm.itim.authentication.service.ServiceAuthenticationProviderFactory
# webseal provider
enrole.authentication.provider.webseal=\
    factory=com.ibm.itim.authentication.webseal.WebsealProviderFactory

# THE FOLLOWING IS FOR WEBSEAL AUTHENTICATION PROVIDER ONLY
# Set to true if all ITAM IDs equal ITIM IDs
# Set to false if any ITAM ID does not equal an ITIM ID
enrole.authentication.idsEqual=true

{{- $enabled := .Values.general.install.useExternalRegistry }}
{{- with default dict .Values.externalRegistry }}
# Property specifying which IDMapper implementing class to be used
# when mapping an external userid to an ITIM ID
enrole.authentication.idmapper=com.ibm.itim.authentication.mapping.{{ $enabled | ternary "LdapId" "DefaultID" }}Mapper

enrole.authentication.registry.external={{ $enabled | ternary "true" "false" }}
enrole.authentication.registry.type={{ .type }}
enrole.authentication.registry.host={{ .registryHost }}
enrole.authentication.registry.port={{ .registryPort }}
enrole.authentication.registry.realm={{ .realm }}
enrole.authentication.registry.useSSL={{ .useSSL | ternary "true" "false" }}
enrole.authentication.registry.baseDN={{ .baseDN }}
enrole.authentication.registry.bindDN={{ .bindDN }}
# Do not provide plaintext password here.
# Intentionally empty, injected dynamically. Use smarterkit to set the password.
enrole.authentication.registry.bindPassword=
enrole.authentication.registry.ignoreCase={{ .ignoreCase | ternary "true" "false" }}
{{-   range $key := slice "groupFilter" "groupIdMap" "groupMemberIdMap" "userFilter" "userIdMap" }}
enrole.authentication.registry.{{ $key }}={{ index .filterProperties $key }}
{{-   end }}
{{-   range $index, $item := default slice .attributeConfiguration.attributes }}
{{-     range $key := slice "defaultValue" "entityType" "id" "name" "propertyName" "syntax" }}
enrole.authentication.registry.attributes.{{ $index }}.{{ $key }}={{ index $item $key }}
{{-     end }}
{{-   end }}
{{- end }}
